config/routes.rb
Rails.application.routes.draw do


  resources :titles
  resources :seats
  resources :leaders

  get 'thank_you' => 'leaders#thank_you'
#  get 'leaders/:' => 'leaders#test'

  #put 'leaders/:id' => 'leaders#rsvp'
  root 'leaders#closed'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/leader.rb
class Leader < ActiveRecord::Base

belongs_to :title
belongs_to :seat

has_secure_token :rsvp_token

extend FriendlyId
  friendly_id :rsvp_token, use: :slugged
  
validates :first_name, :last_name, :seat_id, presence: true
#validates_uniqueness_of :email
  
  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |leader|
      csv << leader.attributes.values_at(*column_names)
    end
  end
end

  def self.gradstud
      if Leader.where(:title_id => [3,4]).count > 1
        return false
      end
  end

    def self.docprof
      if Leader.where(:title_id => [1,2]).count > 1
        return true
      end
  end
  
    def self.guest
      if Leader.where(:title_id =>5).count > 1
        return true
      end
  end


end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
  before_action :set_leader, only: [:show, :edit, :update, :destroy, :test, :rsvp]
   http_basic_authenticate_with name: ENV['admin'], password:  ENV['pass'], only: [:index]
  skip_before_filter :verify_authenticity_token, :only => [:update]
  
   
  
def rsvp
	oui = params[:rsvp]
	@leader.update!(:rsvp => oui)
end

  
  def test
    del = RsvpMailer.rsvp_email(Leader.find_by_contact_email("admin@yairsegal.com")).deliver_now
    if del
      flash[:notice] = "Mail sent"
      redirect_to root_path
    else
      flash[:notice] = "Mail not sent"
      redirect_to root_path
    end
  end
  def index
  
    @leaders = Leader.all
    @sumGradStudent = Leader.where(:title_id => [3,4]).count
    @sumDocProf = Leader.where(:title_id => [1,2]).count
    @sumGuest= Leader.where(:title_id => 5).count
    
    @sumIdentity = Leader.where(:seat_id => 1).count
    @sumDistance = Leader.where(:seat_id => 2).count
    @sumCharisma = Leader.where(:seat_id => 3).count
    @sumRsvp = Leader.where(:rsvp => 1).count
    @sumTotal = Leader.all.count
    
    respond_to do |format|
      format.html
      format.csv { send_data @leaders.to_csv }
      format.xls # { send_data @leaders.to_csv(col_sep: "\t") }
    end
    
  end
  
  
  

  # GET /leaders/1
  # GET /leaders/1.json
  def show
  end

  # GET /leaders/new
  def new
    @leader = Leader.new
    
    #Notifier.welcome_email(@leader).deliver
  end
  
  def closed

  
  end

  # GET /leaders/1/edit
  def edit
  end

  # POST /leaders
  # POST /leaders.json
  def create
    @leader = Leader.new(leader_params)
    
    respond_to do |format|
      if @leader.save
      Notifier.welcome_email(@leader).deliver
        format.html { redirect_to new_leader_path, notice: "Thank you for registering" }
        format.json { render :show, status: :created, location: @leader }
      else
        format.html { render :new }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaders/1
  # PATCH/PUT /leaders/1.json
  def update
    respond_to do |format|
      if @leader.update(leader_params)
	
        format.html { redirect_to @leader, head: :no_content, notice: 'Leader was successfully updated.' }
        #format.json { render :show, status: :ok, location: @leader }
        format.json { respond_with_bip(@leader) }
	format.json { render :show, status: :ok, location: @leader }      
else
        format.html { render :edit }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaders/1
  # DELETE /leaders/1.json
  def destroy
    @leader.destroy
    respond_to do |format|
      format.html { redirect_to leaders_url, notice: 'Leader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def thank_you
    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leader
      @leader = Leader.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leader_params
      params.require(:leader).permit(:seat_id, :title_id, :first_name, :last_name, :contact_email, :phone, :locale, :rsvp)
    end
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/views/leaders/_form.html.erb
<%#= Leader.docprof %>
<%= simple_form_for(@leader) do |f| %>
  <% if @leader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leader.errors.count, "error") %> prohibited this leader from being saved:</h2>

      <ul>
      <% @leader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label><%= t ("seat") %></label><br>
    <%= f.collection_select(
        :seat_id, 
        Seat.all, 
        :id, 
        :name, 
        
        {:include_blank => t("choose")} 
      ) %>
  </div>
  <div class="field">
    <label><%= t ("leader.label.title") %></label><br>
    <%= f.collection_select(:title_id, Title.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>

    <%=  f.hidden_field :locale, :value => I18n.locale %>


  <div class="actions">
    <%= f.submit(t "leader.label.register") %>
  </div>
<% end %>

app/views/leaders/closed.html.erb
<style>

body,html{
    height: 100%;
    margin: 0;
    padding: 0;
}

.container{
  height: 100%;
  position: absolute;
  width: 100%;
}
.v-wrap{
    height: 80%;
    text-align: center;
    white-space: nowrap;
}
.v-wrap:before{
    content: "";
    display: inline-block;
    vertical-align: middle;
    width: 0;
    margin-right: -.25em; /*might want to tweak this. .25em for extra white space */
    height: 100%;
}
.v-box{
    display: inline-block;
    vertical-align: middle;
    white-space: normal;
    padding: 1em 1em;
    font-size:2em;
    background: #EEE;
}
</style>

<div class="v-wrap">
  <div class="v-box">
    ההרשמה לכנס נסגרה.<br>
   לפניות מיוחדות אנא צרו קשר בכתובת המייל:<a href="mailto:israel@zofnat.co.il">israel@zofnat.co.il</a>
  </div>


</div>


app/views/leaders/edit.html.erb
<h1>Editing Leader</h1>

<%= render 'form' %>

<%= link_to 'Show', @leader %> |
<%= link_to 'Back', leaders_path %>

app/views/leaders/index.html.erb
<style>
  .download{
    float:left;
    color:white;
  }
</style>
<p id="notice"><%= notice %></p>

<h2 class="total-part">סה"כ משתתפים: <%= @sumTotal %></h2>
<p class="download">
  Download:
  <%= link_to "Excel", leaders_path(format: "xls") %>
</p>
<table class="table table-responsive">
  <tr><th>Participants total</th>
  <tr>
    <th>בוגר + סטודנט</th>
    <th>דוקטור + פרופסור</th>
    <th>אורחים</th>
    <th>אישרו הגעה</th>
  </tr>
  <tr>
    <td><%= @sumGradStudent %></td>
    <td><%= @sumDocProf%></td>
    <td><%= @sumGuest %></td>
    <td><%= @sumRsvp %></td>
  </tr>
</table>

<table class="table table-responsive">
  <tr><th>Seats totals</th>
  <tr>
    <th>זהות</th>
    <th>מרחק</th>
    <th>כריזמה</th>
    
  </tr>
  <tr>
    <td><%= @sumIdentity %></td>
    <td><%= @sumDistance %></td>
    <td><%= @sumCharisma %></td>
  </tr>
</table>

<h3 class="reg-header"><%= t("registered") %></h3>
<table class="table table-border" id="leaders-list">
  <thead>
    <tr>
      <th><%= t("seat") %></th>
      <th><%= t("leader.title") %></th>
      <th><%= t("leader.first_name") %></th>
      <th><%= t("leader.last_name") %></th>
      <th><%= t("leader.email") %></th>
      <th><%= t("leader.rsvp") %></th>
      <th><%= t("leader.create_date") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaders.each do |leader| %>
      <tr>
        <td><%= leader.seat.name %></td>
        <td><%= leader.title.name %></td>
        <td><%= leader.first_name %></td>
        <td><%= leader.last_name %></td>
        <td><%= leader.contact_email %></td>
        <td><%= check_box_tag "done", "1", leader.rsvp%></td>
        <td><%= leader.created_at %></td>
        <td><%= link_to t("edit"), edit_leader_path(leader) %></td>
        <td><%= link_to t("destroy"), leader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leader', new_leader_path %>

<%#= console %>

app/views/leaders/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Registered">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">מושב</Data></Cell>
        <Cell><Data ss:Type="String">שם פרטי</Data></Cell>
        <Cell><Data ss:Type="String">שם משפחה</Data></Cell>
        <Cell><Data ss:Type="String">אימייל</Data></Cell>
        <Cell><Data ss:Type="String">תאריך הרשמה</Data></Cell>
      </Row>
    <% @leaders.each do |leader| %>
      <Row>
        <Cell><Data ss:Type="String"><%= leader.seat.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= leader.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= leader.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= leader.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= leader.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/leaders/new.html.erb
<%= flash_messages %>

<div class="">
  <div class="form-wrap">
  <h2 class="reg-header"><%= t("registerHeader") %></h2>

  <%= render 'form' %>
  </div>
</div>

app/views/leaders/show.html.erb
<style>
  body{color:white;}
  .rsvpBox{font-size:8em;}
  #stat{}
  .button {
  padding: 5px 5px 5px 25px;
  border: 1px solid #666;
  color:#000;
  text-decoration:none;
  background: #dcdcdc url(icon.png) no-repeat scroll 5px center;
}

.button {
  border: 0 none;
  border-radius: 36px;
  color: #fff;
  cursor: pointer;
  display: inline-block;
  font-size: 14px;
  padding: 12px 45px;
  text-transform: none;
  -webkit-transition: all 100ms ease-in-out;
          transition: all 100ms ease-in-out;
  width: auto;
  /* auto */
  text-align: center;
  /* DELETE WHEN WIDTH AUTO */
}
.button:hover {
  opacity: .7;
}
.button.--dark {
  background: #171717;
  color: #FFFFFF;
}
.button.--green {
  background: #4ac15a;
  color: #FFFFFF;
}
.button.--blue {
  background: #2c3dcf;
  color: #FFFFFF;
}

.program{
  width: 70%;
  margin: auto;
  margin-top: 5%;
  padding: 20px;
  text-align: justify;
}

.program h1{
  color: #333;
  margin-bottom: 20px;
  text-align: center;
  text-transform: capitalize;
}

.program h3{
  font-size: 24px;
  text-align: center;
}

.program p{
  color: #555;
  line-height: 1.5;
  word-spacing: 1px;
  margin-bottom: 20px;
}

.program a{
  color: #e74c3c;
  position: relative;
  font-weight: 600;
  font-size: 55px;
  display: inline-block;
  text-decoration: none;
  -webkit-transition: all .3s linear;
  -moz-transition: all .3s linear;
  transition: all .3s linear;
}

.program a:hover{
  color: #222;
}

.program a:before, a:after{
  content: '';
  background: #e74c3c;
  position: absolute;
  width: 0;
  height: 2px;
  -webkit-transition: all .3s linear;
  -moz-transition: all .3s linear;
  transition: all .3s linear;
}

.program a:before{
  top: 0;
  left: 0;
}

.program a:after{
  top: 100%;
  right: 0;
}

.program a:hover:before, .program a:hover:after{
  width: 100%;
}

.no-padding {
  padding: 0px!important;
}

.Cbottons{
  margin-top: 60px;
}

</style>
<div class="">
  <p id="notice"><%= notice %></p>
  <h2><%= "#{t "hello"} #{@leader.first_name}" %></h2>
  <p>
    <strong><%= t "seat" %>:</strong>
    <%= @leader.seat.name %>
  </p>

  <p>
    <strong><%= t "leader.label.title" %>:</strong>
    <%= @leader.title.name %>
  </p>

  <p>
    <strong><%= t "email.label" %>:</strong>
    <%= @leader.contact_email %>
  </p>
</div>

<div class="">
  <h2>לחצ\י על הכפתור מטה לאשר הגעה</h2>
 
<!-- 
  <a href="http://leadersil.org/leaders/<%= @leader.rsvp_token %>/conf?rsvp=si"
    style="background:#11356D;
      color:white;
      display:inline-block;
      width:auto; 
      text-align:center;
      -webkit-border-radius: 10px;
      -moz-border-radius: 10px;
      border-radius: 10px;
      text-decoration:none;
      border:10px solid #11356D;
      -moz-box-shadow: 3px 0 0 0 #ccc; 
      -webkit-box-shadow: 3px 0 0 0 #ccc; 
      box-shadow: 3px 0 0 0 #ccc; ">Visit our website</a>
      
      <a href="http://leadersil.org/leaders/<%= @leader.rsvp_token %>/conf?rsvp=no" 
    style="background:#11356D;
      color:white;
      display:inline-block;
      width:auto; 
      text-align:center;
      -webkit-border-radius: 10px;
      -moz-border-radius: 10px;
      border-radius: 10px;
      text-decoration:none;
      border:10px solid #11356D;
      -moz-box-shadow: 3px 0 0 0 #ccc; 
      -webkit-box-shadow: 3px 0 0 0 #ccc; 
      box-shadow: 3px 0 0 0 #ccc; ">Visit our website</a>
 -->

<div class='container Cbottons no-padding'>
  <div class="button-container">
    <div class='button --green center' id="rsvpYes">מגיע</div>
    <div class='button --blue center'  id="rsvpNo">לא מגיע</div>
  </div>
</div>

<div class="report">הירשמותך נרשמה במערכת</div>

<div class="container program">
  <h3><a href="/brochure.pdf">לתוכניה</a></h3>
</div>

</div>





<script>

$(document).ready(function() {

  
  $(".best_in_place").best_in_place();
  
  originalState = $("#rsvp").attr( 'data-bip-original-content' );
  
  $("#rsvp").click(function(){
    if( originalState == "false"){
      $("#stat").html("<%= t "rsvpYes" %>");
      originalState = "true";
    }
    else{
      $("#stat").html("<%= t "rsvpNo" %>");
      originalState = "false";
    }
  });
  
  
  $('.report').hide();
  $('.button-container').find(".button").on("click" , function() {
      if($(this).attr("id") == "rsvpYes") {
        $('.report').show();
        $('.report').text("הירשמותך נרשמה במערכת");
	$.ajax({
	      type: "PUT",
	      url: 'http://leadersil.org/leaders/<%= @leader.rsvp_token %>',
	      data: JSON.stringify({ rsvp:true } ),
	      contentType: 'application/json', // format of request payload
	      dataType: 'json', // format of the response
	      success: function(response) {
        	//alert( "Data Saved: " + msg );
	      }
});
      }else{    
        $('.report').show();
        $('.report').text("הנך מאשר/ת כי אינך מגיע לכנס");

            $.ajax( {
              type: "PUT",
              url: "http://leadersil.org/leaders/<%= @leader.rsvp_token %>",
              data: JSON.stringify({ rsvp:false }),
	      contentType: 'application/json', // format of request payload
              dataType: 'json', // format of the response

              success: function( response ) {
              //alert(response);
              }
            });
      }
  });
  
  
  $(".rsvpAnswer").click(function(e){ 

    $.ajax( {
      type: "PUT",
      url: "http://leadersil.org/leaders/<%= @leader.rsvp_token %>.json",
      data: {rsvp:true},
      success: function( response ) {
      alert(response);
      }
    });

});
  
  
  
});

</script>

app/views/leaders/thank_you.html.erb
Thank you for registering